# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,1.5f,0f,0f,-1f,-0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,0.75f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,0.75f,0f,0f,-1f,-0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1f,0f,0f,0.0625f,0f,1f,0f,0.75f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,0.0625f,0f,1f,0f,0f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0f,0f,0f,-1f,-0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}