# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone5) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,1.4518f,0f,0f,-1f,-0.0288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-0.999f,-0.0436f,0f,0.3125f,-0.0436f,0.999f,0f,0.6825f,0f,0f,-1f,0.1207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-0.9989f,0.0457f,-0.0134f,-0.4375f,0.0457f,0.999f,-0.0002f,0.713f,0.0134f,-0.0008f,-0.9999f,0.1275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1f,0f,0f,0.0625f,0f,1f,0f,0.713f,0f,0f,-1f,0.1275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,0.0625f,0f,1f,0f,0.0147f,0f,0f,-1f,0.1007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1f,0f,0f,-0.1875f,0f,1f,0f,0.0147f,0f,0f,-1f,0.1007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}