# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:player rig_hash set value 'da75d0a765cb5b8621ea8d789617f6095492606cd37a9be6ee3675efce460417'
scoreboard objectives add aj.slide.frame dummy